[project]
name = "bitmartmcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ccxt>=4.5.2",
    "fastmcp>=2.11.3",
    "pandas>=2.3.2",
    "python-dotenv>=1.1.1",
    "ta>=0.11.0",
]
